apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd # Must match the namespace where ArgoCD is installed
spec:
  project: clustermon # ArgoCD AppProject name
  source:
    repoURL: 'https://github.com/Chakradhar-Jeereddy/Argocd.git'
    targetRevision: main # Git branch, tag, or commit SHA
    path: namespaces # Path within the repository containing the manifests
  destination:
    server: 'https://23B0E7692CE36D8530B925334822A817.gr7.us-east-1.eks.amazonaws.com' # Target cluster URL (this represents the local cluster)
    namespace: clustermon # Target namespace for the deployed resources
  SyncPolicy:
    automated:
      purn: true # if deleted from git orgocd also deletes it
      selfHeal: true  # Revert the changes that were done manually in cluster.
